      SUBROUTINE CAS_INT(NORB,NATOM,GEOM,ATOMCHG,DMOINT1,DMOINT2,ENG)
      IMPLICIT NONE
      INTEGER NORB,NATOM
      REAL*8  DMOINT1(NORB,NORB),ENG
      REAL*8  DMOINT2(NORB,NORB,NORB,NORB)
      REAL*8  COEFF(NORB,NORB)
      REAL*8  GEOM(NATOM,3)
      INTEGER ATOMCHG(NATOM)
      INTEGER I,J
      INTEGER ITMP(NORB)
      CHARACTER*30 BASELABLE
      CALL SYSTEM('cp GAMESSMO.dat INT_MO')
      OPEN(23,FILE='INCAR')
      READ(23,*)
      READ(23,*)BASELABLE
      CLOSE(23)
      CALL BASIS_INT(NATOM,NORB,GEOM,ATOMCHG,DMOINT1,DMOINT2,BASELABLE)
      print *,"mayj : done BASIS_INT in CAS_INT"  

      CALL E_NU(NATOM,GEOM,ATOMCHG,ENG)
      OPEN(23,FILE='INT_MO')
      DO I=1,NORB
        READ(23,*)(COEFF(J,I),J=1,NORB)
      ENDDO
      CLOSE(23)
      CALL TRANSFORM_RAM(NORB,COEFF,DMOINT1,DMOINT2)
      OPEN(23,FILE='FCIDUMP')
      ITMP=1
      WRITE(23,*)'&FCI NORB= ',NORB
      WRITE(23,*)' ORBSYM= ',(ITMP(I),I=1,NORB)
      WRITE(23,*)' ISYM=1 '
      WRITE(23,*)'&END'
      WRITE(23,*)ENG
      CLOSE(23)
      END 

      SUBROUTINE E_NU(NATOM,COORD,ATOMCHG,EN)
      IMPLICIT NONE
      INTEGER NATOM,I,J,K
      REAL*8 COORD(NATOM,3),EN,R12
      INTEGER ATOMCHG(NATOM)
      EN=0.0D0
      DO I=1,NATOM
        DO J=I+1,NATOM
          R12=0.0D0
          DO K=1,3
            R12=R12+(COORD(I,K)-COORD(J,K))**2
          ENDDO
          EN=EN+ATOMCHG(I)*ATOMCHG(J)/DSQRT(R12)
        ENDDO
      ENDDO
      EN=EN*0.529177249D0
      END

      SUBROUTINE FOUND_INIT(NORB,NATOM,GEOM,ATOMCHG)
      IMPLICIT NONE
      INTEGER NORB,NATOM
      REAL*8  DMOINT1(NORB,NORB),ENG
      REAL*8  DMOINT2(NORB,NORB,NORB,NORB)
      REAL*8  GEOM(NATOM,3)
      INTEGER ATOMCHG(NATOM)
      INTEGER I,J
      INTEGER ITMP(NORB)
      CHARACTER*30 BASELABLE
      write(6,*) "mayj : enter FOUND_INIT"
      call flush(6)

      OPEN(23,FILE='INCAR')
      READ(23,*)
      READ(23,*)BASELABLE
      CLOSE(23)
      write(6,*) "mayj : before BASIS_INT in FOUND_INIT"  
      call flush(6) 
      CALL BASIS_INT(NATOM,NORB,GEOM,ATOMCHG,DMOINT1,DMOINT2,BASELABLE)
      print *,"mayj :   done BASIS_INT in FOUND_INIT"  
      call flush(6) 
      END

