      PROGRAM MAIN
      IMPLICIT NONE
      INTEGER NAO,NATOM,NORDER,I
      INTEGER,ALLOCATABLE :: IORDER(:)
      CHARACTER*30 BASELABLE,CC,FILENAME
      OPEN(23,FILE='INPUT')
      READ(23,*)FILENAME
      READ(23,*)CC,NAO
      READ(23,*)CC,NATOM
      READ(23,*)CC,BASELABLE
      READ(23,*)CC,NORDER
      ALLOCATE(IORDER(NORDER))
      READ(23,*)(IORDER(I),I=1,NORDER)
      CLOSE(23)
      IF(FILENAME=='MOLPRO') THEN
        CALL MOLPRO_GAMESS(NAO,NATOM,BASELABLE,NORDER,IORDER)
        CALL MSDFT_GAMESS(NAO,NATOM,BASELABLE,NORDER,IORDER)
      ELSEIF(FILENAME=='GAMESS') THEN
        CALL MSDFT_GAMESS(NAO,NATOM,BASELABLE,NORDER,IORDER)
      ELSEIF(FILENAME=='MSDFT') THEN
        CALL MSDFT_GAMESS(NAO,NATOM,BASELABLE,NORDER,IORDER)
      ENDIF
      DEALLOCATE(IORDER)
      END

